server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
      probability: 1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hcpspringcloud?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: root
    password: zu3.141592653

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: xpu.edu.hcp.springcloud.entities

eureka:
  client:
    # 是否将自己注册到Eureka Server默认为true
    register-with-eureka: true
    # 是否EurekaServer抓取已有的注册信息，默认为true，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      # 单机版
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: payment8001
    prefer-ip-address: true # 访问路径可以显示IP
    # Eureka客户端想服务端发送心跳的时间间隔，单位为秒，默认是30s
    lease-renewal-interval-in-seconds: 30
    # Eureka服务端收到最后一次心跳后等待时间上限，单位为秒，默认是90s，超时则将服务剔除
    lease-expiration-duration-in-seconds: 90
